-- =========================================================
-- GearShop Maroc - Lead Generation & Marketing Platform Schema
-- Run this script in your Supabase SQL Editor
-- =========================================================

-- 1. Newsletter Subscribers
CREATE TABLE IF NOT EXISTS public.newsletter_subscribers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  interests JSONB DEFAULT '[]'::jsonb,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Product Requests ("Can't find what you're looking for?")
CREATE TABLE IF NOT EXISTS public.product_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_name TEXT NOT NULL,
  brand TEXT DEFAULT '',
  budget TEXT DEFAULT '',
  notes TEXT DEFAULT '',
  email TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Quote Requests ("Request a Quote")
CREATE TABLE IF NOT EXISTS public.quote_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT,
  product_name TEXT NOT NULL,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  company TEXT DEFAULT '',
  quantity INT DEFAULT 1,
  message TEXT DEFAULT '',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Product Alerts ("Notify me when available")
CREATE TABLE IF NOT EXISTS public.product_alerts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT,
  product_name TEXT NOT NULL,
  email TEXT NOT NULL,
  status TEXT DEFAULT 'pending',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Contact Leads
CREATE TABLE IF NOT EXISTS public.contact_leads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT DEFAULT '',
  message TEXT DEFAULT '',
  status TEXT DEFAULT 'New', -- 'New', 'Contacted', 'Closed'
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Cookie Consents
CREATE TABLE IF NOT EXISTS public.cookie_consents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  consent_given BOOLEAN DEFAULT TRUE,
  marketing_allowed BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Email Campaigns
CREATE TABLE IF NOT EXISTS public.email_campaigns (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  subject TEXT NOT NULL,
  segment TEXT DEFAULT 'All',
  type TEXT DEFAULT 'Promotions',
  body TEXT NOT NULL,
  recipient_count INT DEFAULT 0,
  sent_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS) on all tables
ALTER TABLE public.newsletter_subscribers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quote_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.contact_leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cookie_consents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.email_campaigns ENABLE ROW LEVEL SECURITY;

-- Anonymous users can INSERT leads
CREATE POLICY "Allow public insert newsletter" ON public.newsletter_subscribers FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "Allow public insert product requests" ON public.product_requests FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "Allow public insert quote requests" ON public.quote_requests FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "Allow public insert product alerts" ON public.product_alerts FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "Allow public insert contact leads" ON public.contact_leads FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "Allow public insert cookie consents" ON public.cookie_consents FOR INSERT TO anon, authenticated WITH CHECK (true);

-- Allow reading/writing for authenticated/anon for admin convenience
CREATE POLICY "Allow public select newsletter" ON public.newsletter_subscribers FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Allow public update newsletter" ON public.newsletter_subscribers FOR UPDATE TO anon, authenticated USING (true);
CREATE POLICY "Allow public delete newsletter" ON public.newsletter_subscribers FOR DELETE TO anon, authenticated USING (true);

CREATE POLICY "Allow public select product requests" ON public.product_requests FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Allow public select quote requests" ON public.quote_requests FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Allow public select product alerts" ON public.product_alerts FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Allow public select contact leads" ON public.contact_leads FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Allow public update contact leads" ON public.contact_leads FOR UPDATE TO anon, authenticated USING (true);
CREATE POLICY "Allow public select campaigns" ON public.email_campaigns FOR SELECT TO anon, authenticated USING (true);
CREATE POLICY "Allow public insert campaigns" ON public.email_campaigns FOR INSERT TO anon, authenticated WITH CHECK (true);
